use std::path::PathBuf;

use clap::{Args, Parser, Subcommand, ValueEnum};
use kicad_ipc_rs::DrcSeverity;

use crate::units::{parse_point_nm, PointNm};

#[derive(Debug, Parser)]
#[command(version, about = "Demo-friendly KiCad PCB Editor IPC companion")]
pub struct Cli {
    /// Override KiCad IPC socket path/URI.
    #[arg(long, global = true)]
    pub socket: Option<String>,

    /// Authentication token for KiCad IPC.
    #[arg(long, global = true)]
    pub token: Option<String>,

    /// IPC request timeout in milliseconds.
    #[arg(long, global = true, default_value_t = 3000)]
    pub timeout_ms: u64,

    /// Output format.
    #[arg(long, global = true, value_enum, default_value_t = OutputFormat::Human)]
    pub format: OutputFormat,

    /// Confirm commands that modify a board.
    #[arg(long, global = true)]
    pub yes: bool,

    #[command(subcommand)]
    pub command: Command,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum OutputFormat {
    Human,
    Json,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Ping KiCad and report version, project, board, and open documents.
    Doctor,
    /// Summarize board layers, origins, stackup, nets, and item counts.
    BoardSummary,
    /// Inventory footprints, pads, nets, tracks, vias, zones, and groups.
    Inventory,
    /// Summarize current selection.
    Selection(SelectionArgs),
    /// Report net classes and net-specific pads/items.
    NetReport(NetReportArgs),
    /// Suggest or apply named PCB component groups.
    ComponentGroups(ComponentGroupsArgs),
    /// Change the PCB editor selection.
    Select(SelectArgs),
    /// Show or change visual editor state.
    View(ViewArgs),
    /// Inject a DRC marker for tutorial annotation.
    DrcMarker(DrcMarkerArgs),
    /// Zone operations.
    Zones(ZonesArgs),
    /// Save the board or selection as KiCad s-expression text.
    Snapshot(SnapshotArgs),
    /// Preview text extents and shape conversion metadata.
    TextShapes(TextShapesArgs),
}

#[derive(Debug, Args)]
pub struct SelectionArgs {
    /// Include decoded selection details.
    #[arg(long)]
    pub details: bool,
}

#[derive(Debug, Args)]
pub struct NetReportArgs {
    /// Restrict the report to these net names or numeric net codes.
    #[arg(long = "net")]
    pub nets: Vec<String>,

    /// Include copper-connected items for net items.
    #[arg(long)]
    pub connected: bool,
}

#[derive(Debug, Args)]
pub struct ComponentGroupsArgs {
    #[command(subcommand)]
    pub command: ComponentGroupsCommand,
}

#[derive(Debug, Subcommand)]
pub enum ComponentGroupsCommand {
    /// Suggest a JSON group plan from footprint references, values, and nets.
    Suggest(ComponentGroupSuggestArgs),
    /// Create or refresh KiCad PCB groups from a JSON group plan.
    Apply(ComponentGroupApplyArgs),
}

#[derive(Debug, Args)]
pub struct ComponentGroupSuggestArgs {
    /// Also write the JSON plan to this path.
    #[arg(long)]
    pub output: Option<PathBuf>,
}

#[derive(Debug, Args)]
pub struct ComponentGroupApplyArgs {
    /// JSON plan generated by `component-groups suggest`.
    #[arg(long)]
    pub plan: PathBuf,

    /// Delete existing KiCad groups with the same names before creating new ones.
    #[arg(long, default_value_t = true)]
    pub replace_existing: bool,
}

#[derive(Debug, Args)]
pub struct SelectArgs {
    #[command(subcommand)]
    pub command: SelectCommand,
}

#[derive(Debug, Subcommand)]
pub enum SelectCommand {
    /// Add item IDs to the current selection.
    Add(ItemIdArgs),
    /// Remove item IDs from the current selection.
    Remove(ItemIdArgs),
    /// Clear the current selection.
    Clear,
    /// Select footprints by reference designator.
    ByRef(SelectByRefArgs),
    /// Select items by net name or code.
    ByNet(SelectByNetArgs),
}

#[derive(Debug, Args)]
pub struct ItemIdArgs {
    /// KiCad item IDs.
    #[arg(required = true)]
    pub item_ids: Vec<String>,
}

#[derive(Debug, Args)]
pub struct SelectByRefArgs {
    /// Reference designators such as U1, C12, or J3.
    #[arg(required = true)]
    pub refs: Vec<String>,

    /// How to combine matches with the current selection.
    #[arg(long, value_enum, default_value_t = SelectionMode::Replace)]
    pub mode: SelectionMode,
}

#[derive(Debug, Args)]
pub struct SelectByNetArgs {
    /// Net names or numeric net codes.
    #[arg(required = true)]
    pub nets: Vec<String>,

    /// How to combine matches with the current selection.
    #[arg(long, value_enum, default_value_t = SelectionMode::Replace)]
    pub mode: SelectionMode,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum SelectionMode {
    Replace,
    Add,
    Remove,
}

#[derive(Debug, Args)]
pub struct ViewArgs {
    #[command(subcommand)]
    pub command: ViewCommand,
}

#[derive(Debug, Subcommand)]
pub enum ViewCommand {
    /// Show or set the active layer by numeric layer id.
    ActiveLayer {
        /// Layer id to activate. Omit to print the current active layer.
        layer_id: Option<i32>,
    },
    /// Show or set visible layers by numeric layer ids.
    VisibleLayers {
        /// Layer ids to make visible. Omit to print visible layers.
        layer_ids: Vec<i32>,
    },
    /// Apply a demo appearance preset.
    Preset(ViewPresetArgs),
}

#[derive(Debug, Args)]
pub struct ViewPresetArgs {
    #[arg(value_enum)]
    pub preset: ViewPreset,

    /// Required by the focus-net preset.
    #[arg(long)]
    pub net: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum ViewPreset {
    AllLayers,
    FocusNet,
    Ratsnest,
}

#[derive(Debug, Args)]
pub struct DrcMarkerArgs {
    /// Marker severity.
    #[arg(long, value_enum, default_value_t = DrcSeverityArg::Warning)]
    pub severity: DrcSeverityArg,

    /// Marker message.
    #[arg(long, default_value = "IPC tutorial marker")]
    pub message: String,

    /// Marker position, e.g. `10mm,20mm` or `1000000nm,2500000nm`.
    #[arg(long, value_parser = parse_point_nm)]
    pub at: Option<PointNm>,

    /// Attach marker to these item IDs.
    #[arg(long = "item-id")]
    pub item_ids: Vec<String>,

    /// Attach marker to the current selection.
    #[arg(long)]
    pub selected: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum DrcSeverityArg {
    Warning,
    Error,
    Exclusion,
    Ignore,
    Info,
    Action,
    Debug,
    Undefined,
}

impl From<DrcSeverityArg> for DrcSeverity {
    fn from(value: DrcSeverityArg) -> Self {
        match value {
            DrcSeverityArg::Warning => Self::Warning,
            DrcSeverityArg::Error => Self::Error,
            DrcSeverityArg::Exclusion => Self::Exclusion,
            DrcSeverityArg::Ignore => Self::Ignore,
            DrcSeverityArg::Info => Self::Info,
            DrcSeverityArg::Action => Self::Action,
            DrcSeverityArg::Debug => Self::Debug,
            DrcSeverityArg::Undefined => Self::Undefined,
        }
    }
}

#[derive(Debug, Args)]
pub struct ZonesArgs {
    #[command(subcommand)]
    pub command: ZonesCommand,
}

#[derive(Debug, Subcommand)]
pub enum ZonesCommand {
    /// Refill all zones, named zone IDs, or selected zones.
    Refill(ZonesRefillArgs),
}

#[derive(Debug, Args)]
pub struct ZonesRefillArgs {
    /// Refill these zone IDs. Omit with no other flags to refill all zones.
    #[arg(long = "zone-id")]
    pub zone_ids: Vec<String>,

    /// Refill zones in the current selection.
    #[arg(long)]
    pub selected: bool,
}

#[derive(Debug, Args)]
pub struct SnapshotArgs {
    /// Snapshot scope.
    #[arg(long, value_enum, default_value_t = SnapshotScope::Board)]
    pub scope: SnapshotScope,

    /// Output `.kicad_pcb` or s-expression file.
    #[arg(long)]
    pub output: PathBuf,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum SnapshotScope {
    Board,
    Selection,
}

#[derive(Debug, Args)]
pub struct TextShapesArgs {
    /// Text to measure and convert to shape metadata.
    pub text: String,
}
